# Generated by Django 3.2.4 on 2021-07-13 15:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import project.apps.places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='Código de duas letras, conforme ISO 3166-1 alpha-2', max_length=2, primary_key=True, serialize=False, verbose_name='Código internacional')),
                ('name', models.CharField(max_length=32, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(help_text='Código de duas letras.', max_length=2, primary_key=True, serialize=False, verbose_name='Sigla')),
                ('name', models.CharField(max_length=32, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nome')),
                ('country', models.ForeignKey(blank=True, default=project.apps.places.models.get_default_country, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.country', verbose_name='País')),
                ('state', models.ForeignKey(blank=True, default=project.apps.places.models.get_default_state, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.state', verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='', null=True, srid=4326, verbose_name='localização')),
                ('address', models.CharField(blank=True, help_text='Rua e número', max_length=256, null=True, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, help_text='Apto, bloco, casa', max_length=256, null=True, verbose_name='complemento')),
                ('neighbourhood', models.CharField(blank=True, max_length=256, null=True, verbose_name='bairro')),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='código postal')),
                ('instructions', models.CharField(blank=True, help_text='Ou alguma informação que devemos saber ao entregar o pedido.', max_length=256, null=True, verbose_name='ponto de referência')),
                ('extra', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, default=project.apps.places.models.get_default_city, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.city', verbose_name='Cidade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
